(() => {
  'use strict';
  const VERSION='34';
  const STORAGE_KEY='rbtwar-analytics-v29';
  const ENDPOINT_KEY='rbtwar-analytics-endpoint';
  const MAX_EVENTS=1200,MAX_SESSIONS=120,FLUSH_MS=30000,HEARTBEAT_MS=10000;
  const $=id=>document.getElementById(id);
  const iso=()=>new Date().toISOString();
  const uuid=()=>{try{return crypto.randomUUID();}catch(_){return`rbt-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,12)}`;}};
  const blank=()=>({version:VERSION,installId:uuid(),createdAt:iso(),events:[],sessions:[],totals:{sessions:0,levelsStarted:0,wins:0,fails:0,retries:0,exits:0,upgrades:0,adOffers:0,adStarts:0,adCompletes:0,rewardsGranted:0},maxLevelSeen:1});
  function load(){try{const raw=localStorage.getItem(STORAGE_KEY);if(!raw)return blank();const p=JSON.parse(raw),b=blank();return{...b,...p,version:VERSION,installId:p.installId||b.installId,events:Array.isArray(p.events)?p.events:[],sessions:Array.isArray(p.sessions)?p.sessions:[],totals:{...b.totals,...(p.totals||{})}};}catch(_){return blank();}}

  let store=load(),endpoint=window.RBTWAR_ANALYTICS_ENDPOINT||localStorage.getItem(ENDPOINT_KEY)||'',flushBusy=false,activeRun=null,runClockSince=0,sessionEnded=false;
  const sessionId=uuid(),sessionStart=Date.now();let sessionActiveMs=0,sessionActiveSince=document.hidden?0:Date.now();
  const session={id:sessionId,started_at:iso(),last_seen_at:iso(),duration_seconds:0,active_seconds:0,max_level:1,levels_started:0,wins:0,fails:0,upgrades:0,ads_completed:0};
  store.sessions.push(session);if(store.sessions.length>MAX_SESSIONS)store.sessions.splice(0,store.sessions.length-MAX_SESSIONS);store.totals.sessions++;

  function gameState(){try{return window.RBTwarAPI?.getState?.()||null;}catch(_){return null;}}
  function context(){const s=gameState();return{level:Math.max(1,Number(s?.currentLevel||1)),unlocked_level:Math.max(1,Number(s?.unlockedLevel||1)),biome:s?.levelMeta?.biome||null,coins:Number(s?.coins||0),stars_total:Number(s?.stars||0),cycle:Number(s?.levelMeta?.cycle||Math.floor((Number(s?.currentLevel||1)-1)/30)+1),difficulty:s?.levelMeta?.difficulty||null};}
  function activeSessionMs(){return sessionActiveMs+(sessionActiveSince?Math.max(0,Date.now()-sessionActiveSince):0);}
  function persist(){try{session.last_seen_at=iso();session.duration_seconds=Math.max(0,Math.round((Date.now()-sessionStart)/1000));session.active_seconds=Math.max(0,Math.round(activeSessionMs()/1000));localStorage.setItem(STORAGE_KEY,JSON.stringify(store));}catch(e){console.warn('RBTwar analytics: guardado local falló.',e);}}
  function normalize(data){const o={};for(const[k,v]of Object.entries(data||{})){if(v==null)continue;if(typeof v==='string')o[k]=v.slice(0,180);else if(typeof v==='number'&&Number.isFinite(v))o[k]=v;else if(typeof v==='boolean')o[k]=v;else if(Array.isArray(v))o[k]=v.slice(0,12).map(x=>typeof x==='string'?x.slice(0,80):x);}return o;}
  function applyTotals(name,e){if(name==='level_start'){store.totals.levelsStarted++;session.levels_started++;}else if(name==='level_win'){store.totals.wins++;session.wins++;}else if(name==='level_fail'){store.totals.fails++;session.fails++;}else if(name==='level_retry')store.totals.retries++;else if(name==='level_exit')store.totals.exits++;else if(name==='unit_upgrade'){store.totals.upgrades++;session.upgrades++;}else if(name==='ad_offer')store.totals.adOffers++;else if(name==='ad_started')store.totals.adStarts++;else if(name==='ad_completed'){store.totals.adCompletes++;session.ads_completed++;}else if(name==='reward_received')store.totals.rewardsGranted++;const level=Number(e.level||1);store.maxLevelSeen=Math.max(Number(store.maxLevelSeen||1),level);session.max_level=Math.max(Number(session.max_level||1),level);}
  function track(name,data={}){const e={event_id:uuid(),event:String(name).slice(0,60),ts:iso(),app_version:VERSION,install_id:store.installId,session_id:sessionId,...context(),...normalize(data),sent:false};store.events.push(e);if(store.events.length>MAX_EVENTS)store.events.splice(0,store.events.length-MAX_EVENTS);applyTotals(name,e);persist();window.dispatchEvent(new CustomEvent('rbtwar:analytics',{detail:{...e}}));return e;}

  function gameplayClockEligible(){if(document.hidden)return false;for(const id of ['startScreen','resultModal','pauseModal','experienceOverlay']){const el=$(id);if(el&&!el.classList.contains('hidden'))return false;}return true;}
  function syncRunClock(){if(!activeRun){runClockSince=0;return;}const ok=gameplayClockEligible();if(ok&&!runClockSince)runClockSince=Date.now();if(!ok&&runClockSince){activeRun.active_ms+=Math.max(0,Date.now()-runClockSince);runClockSince=0;}}
  function runActiveMs(){return activeRun?activeRun.active_ms+(runClockSince?Math.max(0,Date.now()-runClockSince):0):0;}
  function finishRun(outcome,extra={}){if(!activeRun)return;syncRunClock();const r=activeRun,active=Math.max(0,Math.round(runActiveMs()/1000)),wall=Math.max(0,Math.round((Date.now()-r.started_at_ms)/1000));activeRun=null;runClockSince=0;const common={level:r.level,run_id:r.id,source:r.source,active_seconds:active,wall_seconds:wall,...extra};if(outcome==='win')track('level_win',common);else if(outcome==='fail')track('level_fail',common);else track('level_exit',{...common,reason:outcome||'exit'});}
  function beginRun(source='play'){const level=Math.max(1,Number(gameState()?.currentLevel||1));if(activeRun&&activeRun.level===level&&Date.now()-activeRun.started_at_ms<700)return;if(activeRun)finishRun(source==='restart'||source==='retry'?source:'new_order');activeRun={id:uuid(),level,source,started_at_ms:Date.now(),active_ms:0};runClockSince=0;if(source==='restart'||source==='retry')track('level_retry',{level,source});track('level_start',{level,run_id:activeRun.id,source});syncRunClock();}

  function bind(){const starters={startBtn:'play',restartBtn:'restart',replayBtn:'retry',nextBtn:'next',prevLevelBtn:'previous',nextUnlockedBtn:'next'};for(const[id,source]of Object.entries(starters)){const b=$(id);if(b&&!b.dataset.analyticsBound){b.dataset.analyticsBound='1';b.addEventListener('click',()=>setTimeout(()=>beginRun(source),0));}}const home=$('homeBtn');if(home&&!home.dataset.analyticsBound){home.dataset.analyticsBound='1';home.addEventListener('click',()=>finishRun('home'));}const path=$('levelPath');if(path&&!path.dataset.analyticsBound){path.dataset.analyticsBound='1';path.addEventListener('click',e=>{const b=e.target.closest?.('.level-node');if(!b||b.disabled)return;const level=Number(b.textContent.trim());if(Number.isFinite(level))track('level_select',{level});});}}
  function observeResult(){const m=$('resultModal');if(!m||m.dataset.analyticsObserved)return;m.dataset.analyticsObserved='1';let visible=!m.classList.contains('hidden');const sync=()=>{const now=!m.classList.contains('hidden');if(now&&!visible&&activeRun){const win=String($('resultEyebrow')?.textContent||'').toUpperCase().includes('VICTORIA'),stars=(String($('resultStars')?.textContent||'').split('⭐').length-1),reward=Number((String($('rewardCoins')?.textContent||'').match(/\d+/)||['0'])[0]);finishRun(win?'win':'fail',{stars:Math.max(0,stars),reward_coins:reward});}visible=now;syncRunClock();};new MutationObserver(sync).observe(m,{attributes:true,attributeFilter:['class']});}
  function observeClock(){for(const id of ['startScreen','pauseModal','experienceOverlay','resultModal']){const el=$(id);if(el&&!el.dataset.analyticsClockObserved){el.dataset.analyticsClockObserved='1';new MutationObserver(syncRunClock).observe(el,{attributes:true,attributeFilter:['class','data-mode']});}}}
  function wrapUpgrade(){const api=window.RBTwarAPI;if(!api||api.__analyticsUpgradeWrapped||typeof api.upgradeUnit!=='function')return;const original=api.upgradeUnit.bind(api);api.upgradeUnit=type=>{const before=api.getCatalog?.().find?.(u=>u.type===type)||null,coinsBefore=Number(api.getState?.()?.coins||0),result=original(type);if(result?.ok){const after=api.getCatalog?.().find?.(u=>u.type===type)||null;track('unit_upgrade',{unit_type:type,from_level:Number(before?.level||Math.max(1,Number(result.level||1)-1)),to_level:Number(after?.level||result.level||1),cost:Number(result.cost||before?.cost||0),coins_before:coinsBefore,coins_after:Number(api.getState?.()?.coins||0)});}return result;};Object.defineProperty(api,'__analyticsUpgradeWrapped',{value:true});}

  function pending(){return store.events.filter(e=>!e.sent).slice(0,60);}
  async function flush(){if(flushBusy||!endpoint)return false;const batch=pending();if(!batch.length)return true;flushBusy=true;try{const r=await fetch(endpoint,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({app:'rbtwar',version:VERSION,events:batch.map(({sent,...e})=>e)}),keepalive:true,credentials:'omit'});if(!r.ok)throw new Error(`HTTP ${r.status}`);const ids=new Set(batch.map(e=>e.event_id));store.events.forEach(e=>{if(ids.has(e.event_id))e.sent=true;});persist();return true;}catch(e){console.warn('RBTwar analytics: envío pendiente.',e);return false;}finally{flushBusy=false;}}
  function beacon(){if(!endpoint||!navigator.sendBeacon)return;const batch=pending().slice(0,30);if(!batch.length)return;try{navigator.sendBeacon(endpoint,new Blob([JSON.stringify({app:'rbtwar',version:VERSION,events:batch.map(({sent,...e})=>e)})],{type:'application/json'}));}catch(_){}}
  function summary(){persist();const sessions=store.sessions||[],total=sessions.reduce((n,s)=>n+Number(s.active_seconds||0),0);return{version:VERSION,installId:store.installId,totals:{...store.totals},maxLevelSeen:Number(store.maxLevelSeen||1),sessions:sessions.length,avgSessionActiveSeconds:sessions.length?Math.round(total/sessions.length):0,pendingEvents:pending().length,endpointConfigured:Boolean(endpoint)};}
  function configureEndpoint(url=''){endpoint=String(url||'').trim();if(endpoint)localStorage.setItem(ENDPOINT_KEY,endpoint);else localStorage.removeItem(ENDPOINT_KEY);track('analytics_endpoint_changed',{enabled:Boolean(endpoint)});if(endpoint)flush();return Boolean(endpoint);}
  function trackAd(stage,placement='unknown',reward=''){const map={offer:'ad_offer',click:'ad_clicked',started:'ad_started',completed:'ad_completed',reward:'reward_received',failed:'ad_failed',skipped:'ad_skipped'};return track(map[stage]||`ad_${stage}`,{placement,reward});}
  function syncVisibility(){if(document.hidden){if(sessionActiveSince){sessionActiveMs+=Math.max(0,Date.now()-sessionActiveSince);sessionActiveSince=0;}}else if(!sessionActiveSince)sessionActiveSince=Date.now();syncRunClock();persist();}
  function endSession(reason='pagehide'){if(sessionEnded)return;if(activeRun)finishRun('session_end');syncVisibility();track('session_end',{reason,duration_seconds:Math.max(0,Math.round((Date.now()-sessionStart)/1000)),active_seconds:Math.max(0,Math.round(activeSessionMs()/1000))});sessionEnded=true;persist();beacon();}
  function init(){bind();observeResult();observeClock();wrapUpgrade();if(!store.events.some(e=>e.session_id===sessionId&&e.event==='session_start'))track('session_start',{viewport_w:Math.round(innerWidth||0),viewport_h:Math.round(innerHeight||0),standalone:Boolean(matchMedia?.('(display-mode: standalone)').matches)});console.info('RBTwar analítica v34 lista');}

  window.RBTwarAnalytics={version:VERSION,track,trackAd,getSummary:summary,exportData:()=>{persist();return JSON.parse(JSON.stringify(store));},flush,configureEndpoint,getEndpoint:()=>endpoint,getInstallId:()=>store.installId};
  window.addEventListener('rbtwar:ready',()=>{wrapUpgrade();bind();observeResult();setTimeout(observeClock,0);});
  window.addEventListener('rbtwar:state',()=>{wrapUpgrade();const level=Number(context().level||1);store.maxLevelSeen=Math.max(Number(store.maxLevelSeen||1),level);session.max_level=Math.max(Number(session.max_level||1),level);if(!activeRun&&gameplayClockEligible())beginRun('state');persist();});
  document.addEventListener('visibilitychange',syncVisibility);window.addEventListener('pagehide',()=>endSession('pagehide'));window.addEventListener('beforeunload',()=>endSession('beforeunload'));
  setInterval(()=>{syncRunClock();persist();},HEARTBEAT_MS);setInterval(flush,FLUSH_MS);
  if(window.RBTwarAPI)init();else window.addEventListener('rbtwar:ready',init,{once:true});
})();
