(() => {
'use strict';
const canvas=document.getElementById('gameCanvas');
const ctx=canvas.getContext('2d',{alpha:false});
const ui={
 coinCount:document.getElementById('coinCount'),starCount:document.getElementById('starCount'),worldLabel:document.getElementById('worldLabel'),levelProgressText:document.getElementById('levelProgressText'),
 pauseBtn:document.getElementById('pauseBtn'),pauseModal:document.getElementById('pauseModal'),resumeBtn:document.getElementById('resumeBtn'),restartBtn:document.getElementById('restartBtn'),homeBtn:document.getElementById('homeBtn'),
 tutorial:document.getElementById('tutorial'),tutorialClose:document.getElementById('tutorialClose'),selectionPanel:document.getElementById('selectionPanel'),selectedSquadLabel:document.getElementById('selectedSquadLabel'),selectedSquadType:document.getElementById('selectedSquadType'),cancelSelection:document.getElementById('cancelSelection'),toast:document.getElementById('toast'),
 startScreen:document.getElementById('startScreen'),startBtn:document.getElementById('startBtn'),startProgress:document.getElementById('startProgress'),startCoins:document.getElementById('startCoins'),selectedLevelInfo:document.getElementById('selectedLevelInfo'),levelPath:document.getElementById('levelPath'),
 resultModal:document.getElementById('resultModal'),resultEyebrow:document.getElementById('resultEyebrow'),resultTitle:document.getElementById('resultTitle'),resultStars:document.getElementById('resultStars'),resultMessage:document.getElementById('resultMessage'),rewardCoins:document.getElementById('rewardCoins'),replayBtn:document.getElementById('replayBtn'),nextBtn:document.getElementById('nextBtn'),prevLevelBtn:document.getElementById('prevLevelBtn'),nextUnlockedBtn:document.getElementById('nextUnlockedBtn')
};
const STORAGE_KEY='rbtwar-save-v7',MAX_LEVEL=30;
const TEAM=Object.freeze({PLAYER:'player',ENEMY:'enemy',NEUTRAL:'neutral'});
const TEAM_COLOR=Object.freeze({player:'#36b8ff',enemy:'#ff5d68',neutral:'#c7bfae'});
const UNITS=Object.freeze({
 basic:{name:'Básico',short:'BAS',unlock:1,speed:76,hp:100,damage:17,fireRate:.86,range:88,production:5.4,projectileSpeed:330,size:1},
 fast:{name:'Rápido',short:'VEL',unlock:4,speed:108,hp:72,damage:13,fireRate:.60,range:76,production:4.6,projectileSpeed:370,size:.88},
 heavy:{name:'Pesado',short:'PES',unlock:8,speed:55,hp:190,damage:29,fireRate:1.18,range:82,production:7.6,projectileSpeed:285,size:1.22},
 sniper:{name:'Francotirador',short:'FRA',unlock:12,speed:64,hp:66,damage:42,fireRate:1.72,range:158,production:8.4,projectileSpeed:455,size:.96}
});
const UNIT_ORDER=['basic','fast','heavy','sniper'];
const BIOMES=Object.freeze({
 desert:{name:'Desierto',ground:'#b99b63',ground2:'#9c7f4d',road:'#70583c',roadEdge:'#58452f',obstacle:'#5f513f'},
 canyon:{name:'Cañón',ground:'#a77d53',ground2:'#835f3e',road:'#694b35',roadEdge:'#503827',obstacle:'#614536'},
 forest:{name:'Bosque',ground:'#698856',ground2:'#537044',road:'#6e5b43',roadEdge:'#554633',obstacle:'#315537'},
 snow:{name:'Nieve',ground:'#cbdcdf',ground2:'#a9c1c6',road:'#75898e',roadEdge:'#62767a',obstacle:'#60767c'},
 city:{name:'Ciudad',ground:'#747b84',ground2:'#5d646d',road:'#343b43',roadEdge:'#252b31',obstacle:'#444b53'},
 elite:{name:'Zona Élite',ground:'#595563',ground2:'#494551',road:'#34313a',roadEdge:'#24212a',obstacle:'#393642'}
});
const TITLES=[
 'Tres caminos','Cruce de fábricas','Primera frontera','Carrera de robots','Fortaleza exterior',
 'Garganta seca','Doble desvío','Puente de arena','Rutas cruzadas','Bastión del cañón',
 'Entrada al bosque','Senderos verdes','Emboscada central','Bosque dividido','Fortín vegetal',
 'Frontera helada','Paso congelado','Cruce blanco','Tridente de hielo','Ciudadela nevada',
 'Primer distrito','Avenidas en guerra','Nudo industrial','Cerco urbano','Fortaleza metropolitana',
 'Zona prohibida','Anillo de élite','Último corredor','Asedio total','CORE Supremo'
];
const WORLD_NAMES=['Desierto Inicial','Cañón Avanzado','Bosque','Nieve','Ciudad','Zona Élite'];
const TEMPLATES=[
 {nodes:[[.07,.50,'P'],[.28,.20,'N'],[.38,.50,'N'],[.28,.80,'N'],[.68,.50,'E'],[.93,.50,'H']],edges:[[0,1],[0,2],[0,3],[1,4],[2,4],[3,4],[4,5]]},
 {nodes:[[.07,.52,'P'],[.25,.25,'N'],[.30,.76,'N'],[.49,.44,'N'],[.65,.74,'E'],[.74,.25,'E'],[.93,.52,'H']],edges:[[0,1],[0,2],[1,3],[2,3],[2,4],[3,4],[3,5],[4,6],[5,6]]},
 {nodes:[[.07,.50,'P'],[.24,.50,'N'],[.42,.20,'N'],[.42,.80,'N'],[.60,.50,'N'],[.76,.25,'E'],[.76,.75,'E'],[.94,.50,'H']],edges:[[0,1],[1,2],[1,3],[2,4],[3,4],[4,5],[4,6],[5,7],[6,7]]},
 {nodes:[[.07,.50,'P'],[.23,.24,'N'],[.23,.76,'N'],[.42,.50,'N'],[.58,.22,'N'],[.58,.78,'N'],[.76,.50,'E'],[.94,.50,'H']],edges:[[0,1],[0,2],[1,3],[2,3],[3,4],[3,5],[4,6],[5,6],[6,7]]},
 {nodes:[[.06,.50,'P'],[.22,.18,'N'],[.22,.82,'N'],[.40,.34,'N'],[.40,.66,'N'],[.58,.50,'N'],[.72,.20,'E'],[.72,.80,'E'],[.94,.50,'H']],edges:[[0,1],[0,2],[1,3],[2,4],[3,5],[4,5],[5,6],[5,7],[6,8],[7,8],[3,4]]}
];
const defaultSave=()=>({coins:0,unlockedLevel:1,currentLevel:1,unitLevels:{basic:1,fast:1,heavy:1,sniper:1},firstTimes:{},bestTimes:{},stars:{},tutorialSeen:false});
let save=loadSave(),game=null,inMenu=true,paused=false,ended=false,selectedSquadId=null,drag=null,pointer={x:-999,y:-999},lastTs=performance.now(),toastTimer=null,view={w:844,h:390,dpr:1};
function clamp(v,a,b){return Math.max(a,Math.min(b,v));}
function dist(a,b){return Math.hypot(a.x-b.x,a.y-b.y);}
function randFactory(seed){return()=>{let t=seed+=0x6D2B79F5;t=Math.imul(t^(t>>>15),t|1);t^=t+Math.imul(t^(t>>>7),t|61);return((t^(t>>>14))>>>0)/4294967296;};}
function loadSave(){for(const key of [STORAGE_KEY,'rbtwar-save-v6','rbtwar-save-v5','rbtwar-save-v4','rbtwar-save-v3','rbtwar-save-v2','rbtwar-save-v1']){try{const raw=localStorage.getItem(key);if(raw)return normalizeSave(JSON.parse(raw));}catch(_){}}return defaultSave();}
function normalizeSave(d){const s={...defaultSave(),...(d||{})};s.unlockedLevel=clamp(Number(s.unlockedLevel||1),1,MAX_LEVEL);s.currentLevel=clamp(Number(s.currentLevel||1),1,s.unlockedLevel);s.unitLevels={basic:1,fast:1,heavy:1,sniper:1,...(d?.unitLevels||{})};s.firstTimes={...(d?.firstTimes||{})};s.bestTimes={...(d?.bestTimes||{})};s.stars={...(d?.stars||{})};return s;}
function persist(){localStorage.setItem(STORAGE_KEY,JSON.stringify(save));refreshHud();refreshStartScreen();}
function totalStars(){return Object.values(save.stars).reduce((n,v)=>n+Number(v||0),0);}
function unlockedTypes(level){return UNIT_ORDER.filter(t=>UNITS[t].unlock<=level);}
function biomeKey(level){return ['desert','canyon','forest','snow','city','elite'][Math.min(5,Math.floor((level-1)/5))];}
function worldIndex(level){return Math.min(5,Math.floor((level-1)/5));}
function levelConfig(level){const p=(level-1)/29,early=level<=5;return{title:TITLES[level-1],biome:biomeKey(level),aiDelay:early?13-(level-1)*1.35:6.7-Math.min(3.6,(level-6)*.12),playerProduction:1,enemyProduction:early?1.65-(level-1)*.11:1.14-Math.min(.29,(level-6)*.012),enemyHp:early?.60+(level-1)*.085:1+Math.min(.55,(level-6)*.026),enemyDamage:early?.56+(level-1)*.085:1+Math.min(.48,(level-6)*.022),initialSpawnInterval:early?1.9-(level-1)*.04:1.68,playerCoreHp:900+level*18,enemyCoreHp:early?510+level*35:760+level*30,initialEnemy:early?Math.min(3,1+Math.floor((level-1)/2)):Math.min(5,2+Math.floor(level/7)),difficulty:p};}
function factoryType(level,index,team){const types=unlockedTypes(level);if(team===TEAM.PLAYER&&index===0)return'basic';if(types.length===1)return'basic';const offset=team===TEAM.ENEMY?1:0;return types[(index+level+offset)%types.length];}
function makeLevel(level){const cfg=levelConfig(level),rand=randFactory(2048+level*9173),tpl=TEMPLATES[(level-1)%TEMPLATES.length],nodes=[];tpl.nodes.forEach((n,i)=>{let[nx,ny,role]=n;const shift=level<=2?0:.018;nx+=((rand()-.5)*shift);ny+=((rand()-.5)*shift);const team=role==='P'?TEAM.PLAYER:role==='H'?TEAM.ENEMY:role==='E'?TEAM.ENEMY:TEAM.NEUTRAL;const kind=(role==='P'||role==='H')?'hq':'factory';const q=team===TEAM.PLAYER?5:team===TEAM.ENEMY?(kind==='hq'?Math.min(5,cfg.initialEnemy+1):cfg.initialEnemy):0;const type=factoryType(level,i,team);let maxHp=kind==='hq'?(team===TEAM.PLAYER?cfg.playerCoreHp:cfg.enemyCoreHp):430+level*7;nodes.push({id:`N${i}`,index:i,nx,ny,x:0,y:0,team,kind,unitType:type,spawnQueue:q,spawnCooldown:.85+i*.08,productionTimer:0,captureTeam:null,captureProgress:0,maxHp,hp:maxHp});});
 const obstacles=Array.from({length:7+Math.floor(level/8)},()=>({x:.13+rand()*.74,y:.13+rand()*.74,r:14+rand()*12,rot:rand()*Math.PI}));return{level,config:cfg,title:cfg.title,biome:BIOMES[cfg.biome],nodes,edges:tpl.edges.map(e=>[...e]),roads:[],obstacles,individuals:[],squads:[],projectiles:[],particles:[],elapsed:0,aiThink:.8,idCounter:1,individualIdCounter:1,projectileIdCounter:1};}
function unitStats(type,team,level){const b=UNITS[type],cfg=levelConfig(level),ownLevel=team===TEAM.PLAYER?Math.max(1,save.unitLevels[type]||1):(level<=5?1:1+Math.floor((level-4)/5)),up=1+(ownLevel-1)*.12;return{level:ownLevel,hp:b.hp*up*(team===TEAM.ENEMY?cfg.enemyHp:1),damage:b.damage*up*(team===TEAM.ENEMY?cfg.enemyDamage:1),speed:b.speed*(1+Math.min(.10,(ownLevel-1)*.015)),fireRate:b.fireRate,range:b.range,projectileSpeed:b.projectileSpeed};}
function resizeCanvas(){const r=canvas.getBoundingClientRect(),w=Math.max(1,Math.round(r.width)),h=Math.max(1,Math.round(r.height)),dpr=Math.min(devicePixelRatio||1,2);if(canvas.width!==Math.round(w*dpr)||canvas.height!==Math.round(h*dpr)){canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr);}view={w,h,dpr};ctx.setTransform(dpr,0,0,dpr,0,0);positionNodes();rebuildRoads();repositionWaiting();}
function scale(){return clamp(Math.min(view.w/844,view.h/390),.78,1.18);}
function positionNodes(){if(!game)return;const px=Math.max(30,36*scale()),py=Math.max(25,30*scale()),uw=view.w-px*2,uh=view.h-py*2;for(const n of game.nodes){n.x=px+n.nx*uw;n.y=py+n.ny*uh;}}
function quad(a,c,b,t){const u=1-t;return{x:u*u*a.x+2*u*t*c.x+t*t*b.x,y:u*u*a.y+2*u*t*c.y+t*t*b.y};}
function rebuildRoads(){if(!game)return;const s=scale();game.roads=game.edges.map(([ai,bi],idx)=>{const a=game.nodes[ai],b=game.nodes[bi],dx=b.x-a.x,dy=b.y-a.y,len=Math.hypot(dx,dy)||1,nx=-dy/len,ny=dx/len,sign=((idx*37+game.level*11)%2)?1:-1,bend=Math.min(34*s,len*(.05+((idx+game.level)%3)*.014))*sign,c={x:(a.x+b.x)/2+nx*bend,y:(a.y+b.y)/2+ny*bend},points=[];for(let i=0;i<=18;i++)points.push(quad(a,c,b,i/18));const cumulative=[0];for(let i=1;i<points.length;i++)cumulative.push(cumulative[i-1]+dist(points[i-1],points[i]));return{index:idx,a:ai,b:bi,points,cumulative,total:cumulative.at(-1)};});}
function roadBetween(a,b){return game.roads.find(r=>(r.a===a&&r.b===b)||(r.a===b&&r.b===a));}
function project(px,py,a,b){const vx=b.x-a.x,vy=b.y-a.y,l=vx*vx+vy*vy||1,t=clamp(((px-a.x)*vx+(py-a.y)*vy)/l,0,1),x=a.x+vx*t,y=a.y+vy*t;return{x,y,t,dist:Math.hypot(px-x,py-y)};}
function snapToRoad(x,y){let best=null;for(const road of game.roads)for(let i=0;i<road.points.length-1;i++){const p=project(x,y,road.points[i],road.points[i+1]);if(!best||p.dist<best.dist){const seg=dist(road.points[i],road.points[i+1]),along=road.cumulative[i]+seg*p.t;best={...p,roadIndex:road.index,a:road.a,b:road.b,progress:road.total?along/road.total:0,along};}}return best;}
function neighbors(i){const out=[];for(const r of game.roads){if(r.a===i)out.push({node:r.b,road:r});else if(r.b===i)out.push({node:r.a,road:r});}return out;}
function shortest(from,to){if(from===to)return{nodes:[from],cost:0};const n=game.nodes.length,c=Array(n).fill(Infinity),prev=Array(n).fill(-1),used=Array(n).fill(false);c[from]=0;for(let k=0;k<n;k++){let u=-1,b=Infinity;for(let i=0;i<n;i++)if(!used[i]&&c[i]<b){b=c[i];u=i;}if(u<0||u===to)break;used[u]=true;for(const x of neighbors(u)){const alt=c[u]+x.road.total;if(alt<c[x.node]){c[x.node]=alt;prev[x.node]=u;}}}const nodes=[];let cur=to;while(cur!==-1){nodes.unshift(cur);if(cur===from)break;cur=prev[cur];}return nodes[0]===from?{nodes,cost:c[to]}:{nodes:[from],cost:Infinity};}
function routeAlong(road,fp,tp){const pts=[],forward=tp>=fp,n=road.points.length-1,fi=clamp(Math.floor(fp*n),0,n-1),ti=clamp(Math.floor(tp*n),0,n-1);if(forward){for(let i=fi+1;i<=ti;i++)pts.push({...road.points[i]});}else{for(let i=fi;i>ti;i--)pts.push({...road.points[i]});}const target=tp*road.total;let seg=0;while(seg<road.cumulative.length-2&&road.cumulative[seg+1]<target)seg++;const a=road.points[seg],b=road.points[seg+1],sl=Math.max(.001,road.cumulative[seg+1]-road.cumulative[seg]),t=clamp((target-road.cumulative[seg])/sl,0,1);pts.push({x:a.x+(b.x-a.x)*t,y:a.y+(b.y-a.y)*t});return pts;}
function endpointDistance(snap,endpoint){const r=game.roads[snap.roadIndex];return endpoint===r.a?snap.along:r.total-snap.along;}
function dedupe(points){const out=[];for(const p of points){const last=out.at(-1);if(!last||Math.hypot(last.x-p.x,last.y-p.y)>2)out.push(p);}return out;}
function routeBetween(start,dest){if(!start||!dest)return[];if(start.roadIndex===dest.roadIndex)return routeAlong(game.roads[start.roadIndex],start.progress,dest.progress);const sr=game.roads[start.roadIndex],dr=game.roads[dest.roadIndex];let best=null;for(const se of[sr.a,sr.b])for(const de of[dr.a,dr.b]){const mid=shortest(se,de);if(!Number.isFinite(mid.cost))continue;const cost=endpointDistance(start,se)+mid.cost+endpointDistance(dest,de);if(!best||cost<best.cost)best={cost,se,de,nodes:mid.nodes};}if(!best)return[{x:dest.x,y:dest.y}];const pts=[];pts.push(...routeAlong(sr,start.progress,best.se===sr.a?0:1));for(let i=0;i<best.nodes.length-1;i++){const a=best.nodes[i],b=best.nodes[i+1],r=roadBetween(a,b);if(r)pts.push(...routeAlong(r,a===r.a?0:1,b===r.b?1:0));}pts.push(...routeAlong(dr,best.de===dr.a?0:1,dest.progress));return dedupe(pts);}
function rallyPoint(node,slot=0){const s=scale(),dir=node.x<view.w*.5?1:-1,row=slot%5,col=Math.floor((slot%10)/5);return{x:node.x+dir*(56+col*18)*s,y:node.y+(row-2)*12*s};}
function waitingIndividuals(nodeIndex,team,type=null){return game.individuals.filter(u=>u.homeNode===nodeIndex&&u.team===team&&u.state==='waiting'&&(!type||u.type===type));}
function allIndividualsAtNode(nodeIndex,team){return game.individuals.filter(u=>u.homeNode===nodeIndex&&u.team===team);}
function repositionWaiting(){if(!game)return;const groups=new Map();for(const u of game.individuals){const k=`${u.homeNode}:${u.team}`;if(!groups.has(k))groups.set(k,[]);groups.get(k).push(u);}for(const units of groups.values())units.forEach((u,i)=>{const t=rallyPoint(game.nodes[u.homeNode],i);u.targetX=t.x;u.targetY=t.y;if(u.state==='waiting'){u.x=t.x;u.y=t.y;}});}
function spawnIndividual(node){if(node.team===TEAM.NEUTRAL||node.hp<=0)return;const st=unitStats(node.unitType,node.team,game.level),target=rallyPoint(node,allIndividualsAtNode(node.index,node.team).length);game.individuals.push({id:game.individualIdCounter++,team:node.team,type:node.unitType,level:st.level,homeNode:node.index,x:node.x,y:node.y+7*scale(),targetX:target.x,targetY:target.y,speed:48,state:'exiting',walkPhase:Math.random()*Math.PI*2});spawnBurst(node.x,node.y+7*scale(),TEAM_COLOR[node.team],3);}
function formSquad(node,team,maxCount=5){const avail=waitingIndividuals(node.index,team,node.unitType).slice(0,maxCount);if(!avail.length)return null;const st=unitStats(node.unitType,team,game.level),count=avail.length,ids=new Set(avail.map(u=>u.id)),x=avail.reduce((a,u)=>a+u.x,0)/count,y=avail.reduce((a,u)=>a+u.y,0)/count;game.individuals=game.individuals.filter(u=>!ids.has(u.id));const squad={id:game.idCounter++,team,type:node.unitType,level:st.level,count,unitHp:st.hp,hp:st.hp*count,maxHp:st.hp*count,damage:st.damage,speed:st.speed,fireRate:st.fireRate,range:st.range,projectileSpeed:st.projectileSpeed,x,y,route:[],order:null,fireTimer:.15,combatTargetId:null,selected:false,bob:Math.random()*Math.PI*2};game.squads.push(squad);repositionWaiting();return squad;}
function autoForm(){for(const n of game.nodes)for(const t of[TEAM.PLAYER,TEAM.ENEMY])while(waitingIndividuals(n.index,t,n.unitType).length>=5)formSquad(n,t,5);}
function promoteThreat(){for(const n of game.nodes){if(n.team===TEAM.NEUTRAL)continue;const threat=game.squads.some(s=>s.hp>0&&s.team!==n.team&&dist(s,n)<=115*scale());if(threat){const a=waitingIndividuals(n.index,n.team,n.unitType);if(a.length)formSquad(n,n.team,Math.min(5,a.length));}}}
function getSquad(id){return game.squads.find(s=>s.id===id);}
function getNode(id){return game.nodes.find(n=>n.id===id);}
function selectSquad(s){game.squads.forEach(x=>x.selected=false);s.selected=true;selectedSquadId=s.id;ui.selectedSquadLabel.textContent=`${s.count} robot${s.count===1?'':'s'}`;ui.selectedSquadType.textContent=`${UNITS[s.type].name} Nv. ${s.level}`;ui.selectionPanel.classList.remove('hidden');}
function deselect(){game?.squads.forEach(s=>s.selected=false);selectedSquadId=null;ui.selectionPanel.classList.add('hidden');}
function commandRoad(s,snap,kind='road'){const start=snapToRoad(s.x,s.y);s.route=routeBetween(start,snap);s.order={kind,x:snap.x,y:snap.y};s.combatTargetId=null;}
function commandNode(s,n){commandRoad(s,snapToRoad(n.x,n.y),'node');s.order={kind:'node',targetId:n.id,x:n.x,y:n.y};}
function commandAlly(s,a){if(!s||!a||s.id===a.id)return;s.order={kind:'ally',targetId:a.id,repath:0};s.combatTargetId=null;repathAlly(s,a);}
function repathAlly(s,a){s.route=routeBetween(snapToRoad(s.x,s.y),snapToRoad(a.x,a.y));if(s.order)s.order.repath=.42;}
function productionInterval(n){return UNITS[n.unitType].production*(n.team===TEAM.ENEMY?game.config.enemyProduction:game.config.playerProduction);}
function nextSpawn(n){if(n.team===TEAM.NEUTRAL||n.hp<=0)return null;if(n.spawnQueue>0)return Math.max(0,n.spawnCooldown);return Math.max(0,productionInterval(n)-n.productionTimer);}
function update(dt){if(!game||inMenu||paused||ended)return;game.elapsed+=dt;updateProduction(dt);updateIndividuals(dt);autoForm();promoteThreat();updateAI(dt);updateMovement(dt);updateCombat(dt);updateProjectiles(dt);updateCapture(dt);updateParticles(dt);mergeNearby();cleanup();checkDefeat();}
function updateProduction(dt){for(const n of game.nodes){if(n.team===TEAM.NEUTRAL||n.hp<=0)continue;if(n.spawnQueue>0){n.spawnCooldown-=dt;if(n.spawnCooldown<=0){spawnIndividual(n);n.spawnQueue--;n.spawnCooldown=game.config.initialSpawnInterval;}continue;}n.productionTimer+=dt;const i=productionInterval(n);if(n.productionTimer>=i){n.productionTimer-=i;spawnIndividual(n);}}}
function updateIndividuals(dt){for(const u of game.individuals){u.walkPhase+=dt*8;if(u.state!=='exiting')continue;const dx=u.targetX-u.x,dy=u.targetY-u.y,d=Math.hypot(dx,dy),step=u.speed*dt;if(d<=step+1){u.x=u.targetX;u.y=u.targetY;u.state='waiting';}else{u.x+=dx/d*step;u.y+=dy/d*step;}}}
function updateAI(dt){if(game.elapsed<game.config.aiDelay)return;game.aiThink-=dt;if(game.aiThink>0)return;game.aiThink=Math.max(1.2,2.9-game.level*.05);const idle=game.squads.filter(s=>s.team===TEAM.ENEMY&&s.hp>0&&!s.route.length&&!s.combatTargetId);for(const s of idle){const snap=snapToRoad(s.x,s.y),cur=snap.progress<.5?snap.a:snap.b,candidates=game.nodes.map(n=>({n,path:shortest(cur,n.index)})).filter(x=>x.n.team!==TEAM.ENEMY&&x.path.nodes.length>1).sort((a,b)=>(a.path.cost+(a.n.team===TEAM.NEUTRAL?-65:0)+(a.n.kind==='hq'?120:0))-(b.path.cost+(b.n.team===TEAM.NEUTRAL?-65:0)+(b.n.kind==='hq'?120:0)));if(candidates.length)commandNode(s,candidates[Math.min(candidates.length-1,Math.floor(Math.random()*Math.min(2,candidates.length)))].n);}}
function updateMovement(dt){for(const s of game.squads){s.bob+=dt*4;if(s.hp<=0||s.combatTargetId)continue;if(s.order?.kind==='ally'){const a=getSquad(s.order.targetId);if(!a||a.hp<=0||a.team!==s.team){s.order=null;s.route=[];}else{if(dist(s,a)<=42*scale()){mergePair(s,a,true);continue;}s.order.repath-=dt;if(s.order.repath<=0)repathAlly(s,a);}}if(!s.route.length)continue;const t=s.route[0],dx=t.x-s.x,dy=t.y-s.y,d=Math.hypot(dx,dy),step=s.speed*dt;if(d<=step+2){s.x=t.x;s.y=t.y;s.route.shift();if(!s.route.length&&s.order?.kind!=='ally')s.order=null;}else{s.x+=dx/d*step;s.y+=dy/d*step;}}}
function bodyRadius(s){return(s.count>=4?22:s.count>=2?17:12)*scale()*UNITS[s.type].size;}
function effectiveDistance(a,b){return Math.max(0,dist(a,b)-bodyRadius(a)-bodyRadius(b));}
function nearestEnemy(s){let target=null,best=Infinity;for(const o of game.squads){if(o.team===s.team||o.hp<=0)continue;const d=effectiveDistance(s,o);if(d<=s.range&&d<best){best=d;target=o;}}return target;}
function nodeUnder(s){return game.nodes.find(n=>dist(s,n)<=50*scale())||null;}
function updateCombat(dt){for(const s of game.squads){if(s.hp<=0)continue;s.fireTimer-=dt;let t=s.combatTargetId?getSquad(s.combatTargetId):null;if(t&&(t.hp<=0||effectiveDistance(s,t)>s.range*1.22)){s.combatTargetId=null;t=null;}if(!t){t=nearestEnemy(s);if(t)s.combatTargetId=t.id;}if(t&&s.fireTimer<=0){s.fireTimer=s.fireRate;fireVolley(s,t,'squad');continue;}const n=nodeUnder(s);if(n&&n.kind==='hq'&&n.team!==s.team&&n.team!==TEAM.NEUTRAL&&s.fireTimer<=0){s.fireTimer=s.fireRate;fireVolley(s,n,'node');}}}
function formation(count,gap){const p={1:[[0,0]],2:[[-gap*.5,0],[gap*.5,0]],3:[[-gap*.55,gap*.30],[gap*.55,gap*.30],[0,-gap*.45]],4:[[-gap*.5,-gap*.5],[gap*.5,-gap*.5],[-gap*.5,gap*.5],[gap*.5,gap*.5]],5:[[-gap*.55,-gap*.55],[gap*.55,-gap*.55],[-gap*.55,gap*.55],[gap*.55,gap*.55],[0,0]]};return p[clamp(count,1,5)]||p[1];}
function fireVolley(shooter,target,targetType){const shots=Math.min(shooter.type==='sniper'?1:shooter.type==='heavy'?2:3,shooter.count),mult=targetType==='node'?.34:.46,total=shooter.damage*shooter.count*mult,spread=formation(shots,9*scale());for(let i=0;i<shots;i++){const[ox,oy]=spread[i];game.projectiles.push({id:game.projectileIdCounter++,team:shooter.team,unitType:shooter.type,x:shooter.x+ox,y:shooter.y+oy-3*scale(),prevX:shooter.x+ox,prevY:shooter.y+oy-3*scale(),targetType,targetId:target.id,speed:shooter.projectileSpeed,damage:total/shots,life:2.2,maxLife:2.2});}spawnMuzzle(shooter.x,shooter.y,TEAM_COLOR[shooter.team],shooter.type);}
function updateProjectiles(dt){for(const p of game.projectiles){p.life-=dt;p.prevX=p.x;p.prevY=p.y;const t=p.targetType==='squad'?getSquad(p.targetId):getNode(p.targetId);if(!t||t.hp<=0){p.life=0;continue;}const dx=t.x-p.x,dy=t.y-p.y,d=Math.hypot(dx,dy),step=p.speed*dt;if(d<=step+3){p.x=t.x;p.y=t.y;applyHit(p,t);p.life=0;}else{p.x+=dx/d*step;p.y+=dy/d*step;}}game.projectiles=game.projectiles.filter(p=>p.life>0);}
function applyHit(p,t){t.hp-=p.damage;if(p.targetType==='squad'){syncCount(t);if(t.hp<=0)spawnBurst(t.x,t.y,TEAM_COLOR[t.team],11);}else if(t.hp<=0){t.hp=0;if(p.team===TEAM.PLAYER)winLevel();else loseLevel();}spawnImpact(t.x,t.y,p.team);}
function syncCount(s){const next=clamp(Math.ceil(Math.max(0,s.hp)/s.unitHp),0,5);s.count=next;s.maxHp=s.unitHp*Math.max(1,next);if(next>0)s.hp=Math.min(s.hp,s.maxHp);}
function updateCapture(dt){const radius=50*scale();for(const n of game.nodes){if(n.kind==='hq'||n.hp<=0)continue;const near=game.squads.filter(s=>s.hp>0&&dist(s,n)<=radius),teams=[...new Set(near.map(s=>s.team))];if(teams.length!==1){n.captureProgress=Math.max(0,n.captureProgress-dt*.6);if(n.captureProgress===0)n.captureTeam=null;continue;}const team=teams[0];if(team===n.team){n.captureProgress=0;n.captureTeam=null;continue;}n.captureTeam=team;n.captureProgress+=dt;if(n.captureProgress>=2.6){n.team=team;n.spawnQueue=0;n.spawnCooldown=game.config.initialSpawnInterval;n.productionTimer=0;n.captureProgress=0;n.captureTeam=null;spawnBurst(n.x,n.y,TEAM_COLOR[team],10);if(team===TEAM.PLAYER)showToast(`Fábrica ${UNITS[n.unitType].name} conquistada.`);}}}
function mergePair(m,t,ordered=false){if(!m||!t||m.id===t.id||m.team!==t.team||m.type!==t.type)return false;const cap=Math.max(0,5-t.count);if(cap>0&&m.count>0){const take=Math.min(cap,m.count);t.count+=take;t.hp=Math.min(t.unitHp*t.count,t.hp+m.unitHp*take);t.maxHp=t.unitHp*t.count;m.count-=take;m.hp=Math.max(0,m.hp-m.unitHp*take);m.maxHp=m.unitHp*Math.max(1,m.count);spawnBurst(t.x,t.y,TEAM_COLOR[t.team],5);if(t.team===TEAM.PLAYER)showToast(`${UNITS[t.type].name}: pelotón unido ${t.count}/5.`);}if(m.count<=0||m.hp<=0){m.hp=0;if(selectedSquadId===m.id)selectSquad(t);return true;}if(ordered){const a=Math.atan2(m.y-t.y,m.x-t.x)||Math.PI;m.x=t.x+Math.cos(a)*46*scale();m.y=t.y+Math.sin(a)*46*scale();m.route=[];m.order=null;}return cap>0;}
function mergeNearby(){for(let i=0;i<game.squads.length;i++){const a=game.squads[i];if(a.hp<=0||a.count>=5||a.route.length||a.combatTargetId)continue;for(let j=i+1;j<game.squads.length;j++){const b=game.squads[j];if(b.hp<=0||b.team!==a.team||b.type!==a.type||b.route.length||b.combatTargetId)continue;if(dist(a,b)<=38*scale()&&a.count<5)mergePair(b,a,false);}}}
function updateParticles(dt){for(const p of game.particles){p.life-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.vx*=.96;p.vy*=.96;}game.particles=game.particles.filter(p=>p.life>0);}
function cleanup(){const gone=selectedSquadId&&!game.squads.some(s=>s.id===selectedSquadId&&s.hp>0&&s.count>0);game.squads=game.squads.filter(s=>s.hp>0&&s.count>0);if(gone)deselect();}
function checkDefeat(){if(ended)return;const hq=game.nodes.find(n=>n.kind==='hq'&&n.team===TEAM.PLAYER);if(!hq||hq.hp<=0)loseLevel();}
function computeStars(level,elapsed){const first=save.firstTimes[String(level)];if(!first)return 1;if(elapsed<=first*.80)return 3;if(elapsed<=first*.90)return 2;return 1;}
function winLevel(){if(ended)return;ended=true;const key=String(game.level),elapsed=game.elapsed,first=!save.firstTimes[key];if(first)save.firstTimes[key]=elapsed;save.bestTimes[key]=Math.min(save.bestTimes[key]||Infinity,elapsed);const stars=computeStars(game.level,elapsed);save.stars[key]=Math.max(save.stars[key]||0,stars);const reward=Math.round((90+game.level*18)*(first?1:.35)*(1+(stars-1)*.30));save.coins+=reward;save.unlockedLevel=Math.min(MAX_LEVEL,Math.max(save.unlockedLevel,game.level+1));persist();ui.resultEyebrow.textContent='VICTORIA';ui.resultTitle.textContent=`Nivel ${game.level} completado`;ui.resultStars.textContent='⭐'.repeat(stars);const nextUnlock=UNIT_ORDER.find(t=>UNITS[t].unlock===game.level+1);ui.resultMessage.textContent=nextUnlock?`¡Siguiente nivel desbloquea Robot ${UNITS[nextUnlock].name}!`:first?'Tu primer tiempo quedó guardado internamente como referencia.':stars===3?'Mejoraste al menos 20% tu tiempo inicial.':stars===2?'Mejoraste al menos 10% tu tiempo inicial.':'Puedes repetir el nivel para mejorar tu marca.';ui.rewardCoins.textContent=`+${reward} 🪙`;ui.nextBtn.classList.toggle('hidden',game.level>=MAX_LEVEL);ui.resultModal.classList.remove('hidden');}
function loseLevel(){if(ended)return;ended=true;ui.resultEyebrow.textContent='DERROTA';ui.resultTitle.textContent='Tu castillo CORE fue destruido';ui.resultStars.textContent='';ui.resultMessage.textContent='Repite este nivel o vuelve a uno anterior para reunir monedas.';ui.rewardCoins.textContent='+0 🪙';ui.nextBtn.classList.add('hidden');ui.resultModal.classList.remove('hidden');}
function spawnMuzzle(x,y,color,type){const n=type==='heavy'?7:type==='sniper'?3:4;for(let i=0;i<n;i++)game.particles.push({x,y,vx:(Math.random()-.5)*38,vy:(Math.random()-.5)*38,life:.12+Math.random()*.10,maxLife:.22,color,size:type==='heavy'?3.6:2.8});}
function spawnImpact(x,y,team){const color=TEAM_COLOR[team];for(let i=0;i<6;i++){const a=Math.random()*Math.PI*2,s=24+Math.random()*48;game.particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:.18+Math.random()*.18,maxLife:.36,color,size:2+Math.random()*1.5});}}
function spawnBurst(x,y,color,count=10){for(let i=0;i<count;i++){const a=Math.random()*Math.PI*2,s=18+Math.random()*44;game.particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:.35+Math.random()*.25,maxLife:.60,color,size:2+Math.random()*1.2});}}
function startLevel(level){inMenu=false;save.currentLevel=clamp(level,1,save.unlockedLevel);selectedSquadId=null;drag=null;ended=false;paused=false;game=makeLevel(save.currentLevel);resizeCanvas();ui.startScreen.classList.add('hidden');ui.pauseModal.classList.add('hidden');ui.resultModal.classList.add('hidden');ui.selectionPanel.classList.add('hidden');if(!save.tutorialSeen)ui.tutorial.classList.remove('hidden');updateLabels();persist();lastTs=performance.now();const unlocked=unlockedTypes(game.level).map(t=>UNITS[t].name).join(', ');showToast(`Unidades disponibles: ${unlocked}. Arrastra para mover.`);}
function showStart(){inMenu=true;paused=false;selectedSquadId=null;drag=null;ui.pauseModal.classList.add('hidden');ui.resultModal.classList.add('hidden');ui.selectionPanel.classList.add('hidden');ui.tutorial.classList.add('hidden');ui.startScreen.classList.remove('hidden');refreshStartScreen();}
function updateLabels(){if(!game)return;ui.worldLabel.textContent=`${game.biome.name} · Nivel ${game.level}`;ui.levelProgressText.textContent=`Nivel ${game.level} · ${game.title}`;ui.prevLevelBtn.disabled=game.level<=1;ui.nextUnlockedBtn.disabled=game.level>=save.unlockedLevel||game.level>=MAX_LEVEL;}
function refreshHud(){ui.coinCount.textContent=String(save.coins);ui.starCount.textContent=String(totalStars());if(game)updateLabels();}
function refreshStartScreen(){if(!ui.levelPath)return;ui.startProgress.textContent=`${save.unlockedLevel} de ${MAX_LEVEL} niveles desbloqueados`;ui.startCoins.textContent=`${save.coins} monedas`;const wi=worldIndex(save.currentLevel),types=unlockedTypes(save.currentLevel).map(t=>UNITS[t].name).join(' · ');ui.selectedLevelInfo.textContent=`Nivel ${save.currentLevel} · ${TITLES[save.currentLevel-1]} · ${WORLD_NAMES[wi]} · ${types}`;ui.startBtn.textContent=`JUGAR NIVEL ${save.currentLevel}`;ui.levelPath.innerHTML='';for(let level=1;level<=MAX_LEVEL;level++){const step=document.createElement('div');step.className='level-step';const b=document.createElement('button');b.type='button';b.className='level-node';const unlocked=level<=save.unlockedLevel,completed=Number(save.stars[String(level)]||0)>0;if(unlocked)b.classList.add('unlocked');if(completed)b.classList.add('completed');if(level===save.currentLevel)b.classList.add('selected');if(!unlocked)b.classList.add('locked');if(level>1&&[6,11,16,21,26].includes(level))b.classList.add('world-start');b.disabled=!unlocked;b.innerHTML=unlocked?String(level):'<span class="level-lock">🔒</span>';if(unlocked)b.addEventListener('click',()=>{save.currentLevel=level;localStorage.setItem(STORAGE_KEY,JSON.stringify(save));refreshStartScreen();});const st=document.createElement('span');st.className='level-stars';const c=Number(save.stars[String(level)]||0);st.textContent=c?'★'.repeat(c):(unlocked?'·':'');step.append(b,st);ui.levelPath.appendChild(step);}requestAnimationFrame(()=>ui.levelPath.querySelector('.level-node.selected')?.scrollIntoView({behavior:'smooth',block:'nearest',inline:'center'}));}
function traceRoad(r){ctx.beginPath();ctx.moveTo(r.points[0].x,r.points[0].y);for(let i=1;i<r.points.length;i++)ctx.lineTo(r.points[i].x,r.points[i].y);}
function drawGround(){ctx.fillStyle=game.biome.ground;ctx.fillRect(0,0,view.w,view.h);const s=scale(),step=66*s;ctx.globalAlpha=.14;ctx.fillStyle=game.biome.ground2;for(let y=0;y<view.h+step;y+=step)for(let x=0;x<view.w+step;x+=step){ctx.beginPath();ctx.ellipse(x+((y/step)%2)*step*.3,y,step*.32,step*.16,0,0,Math.PI*2);ctx.fill();}ctx.globalAlpha=1;}
function drawRoads(){const s=scale();ctx.lineCap='round';ctx.lineJoin='round';for(const r of game.roads){ctx.strokeStyle='rgba(0,0,0,.20)';ctx.lineWidth=48*s;traceRoad(r);ctx.stroke();ctx.strokeStyle=game.biome.roadEdge;ctx.lineWidth=41*s;traceRoad(r);ctx.stroke();ctx.strokeStyle=game.biome.road;ctx.lineWidth=35*s;traceRoad(r);ctx.stroke();ctx.strokeStyle='rgba(255,255,255,.08)';ctx.lineWidth=2*s;ctx.setLineDash([7*s,12*s]);traceRoad(r);ctx.stroke();ctx.setLineDash([]);}}
function drawObstacles(){const s=scale();for(const o of game.obstacles){const x=o.x*view.w,y=o.y*view.h,r=o.r*s;if(game.nodes.some(n=>Math.hypot(n.x-x,n.y-y)<r+52*s))continue;ctx.save();ctx.translate(x,y);ctx.rotate(o.rot);ctx.fillStyle='rgba(0,0,0,.15)';ctx.beginPath();ctx.ellipse(3*s,6*s,r,r*.55,0,0,Math.PI*2);ctx.fill();ctx.fillStyle=game.biome.obstacle;ctx.beginPath();ctx.roundRect(-r,-r*.40,r*2,r*.80,r*.28);ctx.fill();ctx.fillStyle='rgba(255,255,255,.08)';ctx.beginPath();ctx.ellipse(-r*.25,-r*.12,r*.38,r*.11,0,0,Math.PI*2);ctx.fill();ctx.restore();}}
function drawRange(){const s=selectedSquadId?getSquad(selectedSquadId):null;if(!s||s.hp<=0)return;ctx.save();ctx.strokeStyle='rgba(130,220,255,.38)';ctx.fillStyle='rgba(65,184,255,.045)';ctx.lineWidth=1.5;ctx.setLineDash([6,6]);ctx.beginPath();ctx.arc(s.x,s.y,s.range+bodyRadius(s),0,Math.PI*2);ctx.fill();ctx.stroke();ctx.restore();}
function commandPoint(t){if(!t)return null;if(t.kind==='ally')return{x:t.squad.x,y:t.squad.y};if(t.kind==='node')return{x:t.node.x,y:t.node.y};if(t.kind==='road')return{x:t.snap.x,y:t.snap.y};return null;}
function drawCommand(){if(!drag?.active||!drag.squadId)return;const s=getSquad(drag.squadId);if(!s)return;const p=commandPoint(drag.target);ctx.save();if(p){const ally=drag.target.kind==='ally';ctx.strokeStyle=ally?'rgba(105,230,255,.94)':'rgba(255,255,255,.88)';ctx.lineWidth=3*scale();ctx.setLineDash([8*scale(),6*scale()]);ctx.beginPath();ctx.moveTo(s.x,s.y);ctx.lineTo(p.x,p.y);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle=ally?'rgba(54,184,255,.32)':'rgba(255,255,255,.22)';ctx.strokeStyle=ally?'#65dfff':'#fff';ctx.lineWidth=2*scale();ctx.beginPath();ctx.arc(p.x,p.y,16*scale(),0,Math.PI*2);ctx.fill();ctx.stroke();}else{ctx.strokeStyle='rgba(255,90,90,.9)';ctx.lineWidth=2*scale();ctx.beginPath();ctx.arc(drag.x,drag.y,12*scale(),0,Math.PI*2);ctx.stroke();}ctx.restore();}
function drawCastle(n,color,s){const r=39*s;ctx.save();ctx.translate(n.x,n.y);ctx.fillStyle='rgba(0,0,0,.23)';ctx.beginPath();ctx.ellipse(4*s,18*s,r*1.35,r*.62,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#313d45';ctx.strokeStyle='rgba(255,255,255,.13)';ctx.lineWidth=1.3*s;ctx.beginPath();ctx.roundRect(-r*1.08,-r*.50,r*2.16,r*1.18,8*s);ctx.fill();ctx.stroke();ctx.fillStyle='#202b33';ctx.strokeStyle=color;ctx.lineWidth=3*s;ctx.beginPath();ctx.roundRect(-r*.72,-r*.60,r*1.44,r*1.10,5*s);ctx.fill();ctx.stroke();for(const side of[-1,1]){const tx=side*r*.82;ctx.fillStyle='#27343d';ctx.strokeStyle=color;ctx.lineWidth=2.5*s;ctx.beginPath();ctx.roundRect(tx-r*.30,-r*.78,r*.60,r*1.05,5*s);ctx.fill();ctx.stroke();ctx.fillStyle='#394852';ctx.fillRect(tx-r*.31,-r*.91,r*.13,r*.16);ctx.fillRect(tx-r*.08,-r*.91,r*.16,r*.16);ctx.fillRect(tx+r*.18,-r*.91,r*.13,r*.16);}ctx.fillStyle='#3b4952';for(let i=-2;i<=2;i++)ctx.fillRect(i*r*.22-r*.08,-r*.75,r*.16,r*.16);ctx.fillStyle='#0c141a';ctx.beginPath();ctx.roundRect(-r*.25,-r*.17,r*.50,r*.55,4*s);ctx.fill();ctx.strokeStyle=color;ctx.lineWidth=2.3*s;ctx.stroke();const pulse=1+Math.sin(game.elapsed*3)*.06;ctx.fillStyle=color;ctx.globalAlpha=.30;ctx.beginPath();ctx.arc(0,r*.03,r*.15*pulse,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1;ctx.fillStyle='#f1f7fb';ctx.font=`900 ${8.5*s}px system-ui`;ctx.textAlign='center';ctx.fillText('CORE',0,-r*.40);ctx.strokeStyle='#e8f2f7';ctx.beginPath();ctx.moveTo(r*.95,-r*.80);ctx.lineTo(r*.95,-r*1.38);ctx.stroke();ctx.fillStyle=color;ctx.beginPath();ctx.moveTo(r*.95,-r*1.36);ctx.lineTo(r*1.43,-r*1.20);ctx.lineTo(r*.95,-r*1.04);ctx.closePath();ctx.fill();const w=r*1.65;ctx.fillStyle='rgba(0,0,0,.45)';ctx.beginPath();ctx.roundRect(-w/2,r*.78,w,5*s,2*s);ctx.fill();ctx.fillStyle=color;ctx.beginPath();ctx.roundRect(-w/2,r*.78,w*clamp(n.hp/n.maxHp,0,1),5*s,2*s);ctx.fill();ctx.restore();}
function drawFactory(n,color,s){const r=31*s,label=UNITS[n.unitType].short;ctx.save();ctx.translate(n.x,n.y);ctx.fillStyle='rgba(0,0,0,.22)';ctx.beginPath();ctx.ellipse(4*s,14*s,r*1.35,r*.60,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#2b3841';ctx.strokeStyle='rgba(255,255,255,.12)';ctx.beginPath();ctx.roundRect(-r*1.05,-r*.46,r*2.10,r*1.05,7*s);ctx.fill();ctx.stroke();ctx.fillStyle='#1b252d';ctx.strokeStyle=color;ctx.lineWidth=2.8*s;ctx.beginPath();ctx.roundRect(-r*.76,-r*.56,r*1.52,r*.96,6*s);ctx.fill();ctx.stroke();ctx.fillStyle='#374650';ctx.beginPath();ctx.moveTo(-r*.76,-r*.56);ctx.lineTo(-r*.46,-r*.78);ctx.lineTo(r*.48,-r*.78);ctx.lineTo(r*.76,-r*.56);ctx.closePath();ctx.fill();ctx.fillStyle='#0a1116';ctx.strokeStyle=color;ctx.lineWidth=2*s;ctx.beginPath();ctx.roundRect(-r*.38,-r*.15,r*.76,r*.55,3*s);ctx.fill();ctx.stroke();ctx.fillStyle='#e8f5ff';ctx.font=`900 ${8.5*s}px system-ui`;ctx.textAlign='center';ctx.fillText(label,0,-r*.49);ctx.fillStyle=color;ctx.beginPath();ctx.arc(-r*.58,-r*.33,2.2*s,0,Math.PI*2);ctx.fill();ctx.beginPath();ctx.arc(r*.58,-r*.33,2.2*s,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#e3edf2';ctx.beginPath();ctx.moveTo(r*.80,-r*.66);ctx.lineTo(r*.80,-r*1.22);ctx.stroke();ctx.fillStyle=color;ctx.beginPath();ctx.moveTo(r*.80,-r*1.20);ctx.lineTo(r*1.28,-r*1.05);ctx.lineTo(r*.80,-r*.88);ctx.closePath();ctx.fill();ctx.restore();}
function waitingCount(n){return waitingIndividuals(n.index,n.team,n.unitType).length;}
function drawBadge(n,s){if(n.team===TEAM.NEUTRAL||n.hp<=0)return;const y=n.y+(n.kind==='hq'?53:43)*s,w=Math.min(5,waitingCount(n)),sec=nextSpawn(n),int=n.spawnQueue>0?game.config.initialSpawnInterval:productionInterval(n),prog=sec==null?0:clamp(1-sec/Math.max(.01,int),0,1);ctx.fillStyle='rgba(5,12,18,.86)';ctx.beginPath();ctx.roundRect(n.x-35*s,y,70*s,20*s,8*s);ctx.fill();ctx.fillStyle='#e4f0f8';ctx.font=`800 ${8.2*s}px system-ui`;ctx.textAlign='left';ctx.textBaseline='middle';ctx.fillText(`${UNITS[n.unitType].short} ${w}/5`,n.x-29*s,y+10*s);ctx.textAlign='right';ctx.fillText(sec==null?'':`${sec.toFixed(1)}s`,n.x+29*s,y+10*s);ctx.strokeStyle='rgba(255,255,255,.18)';ctx.lineWidth=2.8*s;ctx.beginPath();ctx.arc(n.x+4*s,y+10*s,6*s,-Math.PI/2,Math.PI*1.5);ctx.stroke();ctx.strokeStyle=TEAM_COLOR[n.team];ctx.beginPath();ctx.arc(n.x+4*s,y+10*s,6*s,-Math.PI/2,-Math.PI/2+Math.PI*2*prog);ctx.stroke();}
function drawBases(){const s=scale();for(const n of game.nodes){const c=TEAM_COLOR[n.team];n.kind==='hq'?drawCastle(n,c,s):drawFactory(n,c,s);if(n.captureTeam){const r=(n.kind==='hq'?57:47)*s,p=clamp(n.captureProgress/2.6,0,1);ctx.strokeStyle=TEAM_COLOR[n.captureTeam];ctx.lineWidth=4*s;ctx.beginPath();ctx.arc(n.x,n.y,r,-Math.PI/2,-Math.PI/2+Math.PI*2*p);ctx.stroke();}drawBadge(n,s);}}
function drawRobot(x,y,color,size,type,phase=0,moving=false){const info=UNITS[type],sz=size*info.size,bob=moving?Math.sin(phase)*.9*sz:0,leg=moving?Math.sin(phase)*2.4*sz:0,py=y+bob;ctx.fillStyle='rgba(0,0,0,.23)';ctx.beginPath();ctx.ellipse(x+1.5*sz,py+8*sz,7*sz,3.2*sz,0,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#18232c';ctx.lineWidth=3*sz;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(x-3*sz,py+4*sz);ctx.lineTo(x-4*sz-leg,py+9*sz);ctx.moveTo(x+3*sz,py+4*sz);ctx.lineTo(x+4*sz+leg,py+9*sz);ctx.stroke();ctx.fillStyle=type==='heavy'?'#34404a':'#263746';ctx.strokeStyle=color;ctx.lineWidth=2*sz;ctx.beginPath();ctx.roundRect(x-6*sz,py-3*sz,12*sz,10*sz,type==='heavy'?2*sz:3*sz);ctx.fill();ctx.stroke();ctx.fillStyle='#304756';ctx.beginPath();ctx.roundRect(x-5.5*sz,py-10*sz,11*sz,8*sz,3*sz);ctx.fill();ctx.stroke();ctx.fillStyle=color;ctx.globalAlpha=.88;ctx.beginPath();ctx.roundRect(x-3.8*sz,py-7.7*sz,7.6*sz,2.4*sz,1.2*sz);ctx.fill();ctx.globalAlpha=1;if(type==='fast'){ctx.strokeStyle=color;ctx.lineWidth=1.5*sz;ctx.beginPath();ctx.moveTo(x-7*sz,py+2*sz);ctx.lineTo(x-11*sz,py+5*sz);ctx.moveTo(x+7*sz,py+2*sz);ctx.lineTo(x+11*sz,py+5*sz);ctx.stroke();}else if(type==='heavy'){ctx.fillStyle='#17222b';ctx.beginPath();ctx.arc(x-8*sz,py,3.5*sz,0,Math.PI*2);ctx.fill();ctx.beginPath();ctx.arc(x+8*sz,py,3.5*sz,0,Math.PI*2);ctx.fill();}ctx.strokeStyle='#d7e7ef';ctx.lineWidth=(type==='sniper'?1.7:2)*sz;ctx.beginPath();ctx.moveTo(x+5*sz,py+1*sz);ctx.lineTo(x+(type==='sniper'?14:10)*sz,py-(type==='sniper'?2:1)*sz);ctx.stroke();ctx.fillStyle=color;ctx.beginPath();ctx.arc(x+(type==='sniper'?14.5:10.5)*sz,py-(type==='sniper'?2.2:1.2)*sz,1.3*sz,0,Math.PI*2);ctx.fill();}
function drawIndividuals(){const s=scale();for(const u of game.individuals)drawRobot(u.x,u.y,TEAM_COLOR[u.team],.84*s,u.type,u.walkPhase,u.state==='exiting');}
function drawSquads(){const s=scale();for(const q of game.squads){const color=TEAM_COLOR[q.team],offs=formation(q.count,17*s*UNITS[q.type].size);if(q.selected){ctx.fillStyle='rgba(255,255,255,.07)';ctx.strokeStyle='#fff';ctx.lineWidth=2*s;ctx.beginPath();ctx.arc(q.x,q.y,33*s,0,Math.PI*2);ctx.fill();ctx.stroke();}const moving=q.route.length>0||q.order?.kind==='ally';offs.forEach(([ox,oy],i)=>drawRobot(q.x+ox,q.y+oy,color,1.05*s,q.type,q.bob+i*.7,moving));const hp=clamp(q.hp/Math.max(1,q.maxHp),0,1);if(hp<.99){const w=42*s;ctx.fillStyle='rgba(0,0,0,.45)';ctx.fillRect(q.x-w/2,q.y-37*s,w,4*s);ctx.fillStyle=color;ctx.fillRect(q.x-w/2,q.y-37*s,w*hp,4*s);}}}
function drawProjectiles(){const s=scale();ctx.lineCap='round';for(const p of game.projectiles){const color=TEAM_COLOR[p.team],wide=p.unitType==='heavy'?6:p.unitType==='sniper'?3:5;ctx.globalAlpha=.30;ctx.strokeStyle=color;ctx.lineWidth=wide*s;ctx.beginPath();ctx.moveTo(p.prevX,p.prevY);ctx.lineTo(p.x,p.y);ctx.stroke();ctx.globalAlpha=.95;ctx.strokeStyle=p.unitType==='sniper'?'#fff6b6':'#f7fbff';ctx.lineWidth=(p.unitType==='sniper'?1.8:1.4)*s;ctx.beginPath();ctx.moveTo(p.prevX,p.prevY);ctx.lineTo(p.x,p.y);ctx.stroke();ctx.fillStyle=color;ctx.shadowColor=color;ctx.shadowBlur=9*s;ctx.beginPath();ctx.arc(p.x,p.y,(p.unitType==='heavy'?4:p.unitType==='sniper'?2.7:3.2)*s,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;}ctx.globalAlpha=1;}
function drawParticles(){const s=scale();for(const p of game.particles){ctx.globalAlpha=clamp(p.life/p.maxLife,0,1);ctx.fillStyle=p.color;ctx.beginPath();ctx.arc(p.x,p.y,(p.size||2.2)*s,0,Math.PI*2);ctx.fill();}ctx.globalAlpha=1;}
function draw(){if(!game)return;ctx.setTransform(view.dpr,0,0,view.dpr,0,0);drawGround();drawRoads();drawObstacles();drawRange();drawCommand();drawBases();drawIndividuals();drawSquads();drawProjectiles();drawParticles();}
function pointerPos(e){const r=canvas.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top};}
function playerSquadAt(p,exclude=null){const radius=74*scale();return game.squads.filter(s=>s.team===TEAM.PLAYER&&s.hp>0&&s.id!==exclude).map(s=>({s,d:dist(p,s)})).filter(x=>x.d<=radius).sort((a,b)=>a.d-b.d)[0]?.s||null;}
function nodeAt(p){return game.nodes.map(n=>({n,d:dist(p,n)})).filter(x=>x.d<=74*scale()).sort((a,b)=>a.d-b.d)[0]?.n||null;}
function targetAt(p,s){const ally=playerSquadAt(p,s.id);if(ally)return{kind:'ally',squad:ally};const n=nodeAt(p);if(n)return{kind:'node',node:n};const snap=snapToRoad(p.x,p.y);if(snap&&snap.dist<=58*scale())return{kind:'road',snap};return null;}
function execute(s,t){if(!s||!t)return false;if(t.kind==='ally'){if(s.type!==t.squad.type){showToast('Solo se unen pelotones del mismo tipo.');commandAlly(s,t.squad);}else commandAlly(s,t.squad);return true;}if(t.kind==='node'){commandNode(s,t.node);return true;}if(t.kind==='road'){commandRoad(s,t.snap,'road');return true;}return false;}
function onDown(e){if(!game||inMenu||paused||ended)return;e.preventDefault();const p=pointerPos(e);pointer=p;const squad=playerSquadAt(p),own=!squad?nodeAt(p):null;drag={pointerId:e.pointerId,squadId:squad?.id||null,sourceNodeId:own?.team===TEAM.PLAYER?own.id:null,startX:p.x,startY:p.y,x:p.x,y:p.y,active:false,target:null};if(squad)selectSquad(squad);canvas.setPointerCapture?.(e.pointerId);}
function onMove(e){const p=pointerPos(e);pointer=p;if(!drag||drag.pointerId!==e.pointerId)return;drag.x=p.x;drag.y=p.y;if(!drag.active&&Math.hypot(p.x-drag.startX,p.y-drag.startY)>12*scale()){drag.active=true;if(!drag.squadId&&drag.sourceNodeId){const n=getNode(drag.sourceNodeId),a=n?waitingIndividuals(n.index,TEAM.PLAYER,n.unitType):[];if(a.length){const s=formSquad(n,TEAM.PLAYER,Math.min(5,a.length));if(s){drag.squadId=s.id;selectSquad(s);}}}}if(drag.active&&drag.squadId){const s=getSquad(drag.squadId);drag.target=s?targetAt(p,s):null;}}
function onUp(e){if(!game||inMenu||paused||ended){drag=null;return;}e.preventDefault();const p=pointerPos(e);pointer=p;if(!drag||drag.pointerId!==e.pointerId){drag=null;return;}if(drag.active&&drag.squadId){const s=getSquad(drag.squadId),t=drag.target||(s?targetAt(p,s):null);if(s&&t){execute(s,t);deselect();}else showToast('Suelta sobre un camino, una base o un aliado.');}else if(drag.squadId){selectSquad(getSquad(drag.squadId));showToast('Mantén y arrastra el pelotón para moverlo.');}else if(drag.sourceNodeId){const n=getNode(drag.sourceNodeId),sec=n?nextSpawn(n):null;showToast(sec==null?'No hay robots listos.':`Próximo ${UNITS[n.unitType].name} en ${sec.toFixed(1)} s.`);}drag=null;}
function showToast(m){ui.toast.textContent=m;ui.toast.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>ui.toast.classList.remove('show'),2100);}
function loop(ts){const dt=Math.min(.033,(ts-lastTs)/1000||0);lastTs=ts;resizeCanvas();update(dt);draw();requestAnimationFrame(loop);}
canvas.addEventListener('pointerdown',onDown);canvas.addEventListener('pointermove',onMove);canvas.addEventListener('pointerup',onUp);canvas.addEventListener('pointercancel',()=>drag=null);canvas.addEventListener('contextmenu',e=>e.preventDefault());
ui.startBtn.addEventListener('click',()=>startLevel(save.currentLevel));ui.cancelSelection.addEventListener('click',deselect);ui.tutorialClose.addEventListener('click',()=>{ui.tutorial.classList.add('hidden');save.tutorialSeen=true;persist();});ui.pauseBtn.addEventListener('click',()=>{if(inMenu||ended)return;paused=true;ui.pauseModal.classList.remove('hidden');});ui.resumeBtn.addEventListener('click',()=>{paused=false;ui.pauseModal.classList.add('hidden');lastTs=performance.now();});ui.restartBtn.addEventListener('click',()=>startLevel(game.level));ui.homeBtn.addEventListener('click',showStart);ui.replayBtn.addEventListener('click',()=>startLevel(game.level));ui.nextBtn.addEventListener('click',()=>startLevel(Math.min(save.unlockedLevel,game.level+1,MAX_LEVEL)));ui.prevLevelBtn.addEventListener('click',()=>startLevel(game.level-1));ui.nextUnlockedBtn.addEventListener('click',()=>startLevel(Math.min(MAX_LEVEL,game.level+1)));window.addEventListener('resize',resizeCanvas,{passive:true});window.addEventListener('orientationchange',()=>setTimeout(resizeCanvas,120),{passive:true});
game=makeLevel(save.currentLevel);resizeCanvas();refreshHud();refreshStartScreen();showStart();requestAnimationFrame(loop);
})();